name: Setup Cache

on: [workflow_call]

jobs:
  setup-cache:
    runs-on: ubuntu-latest
    steps:
      - name: Set up cache
        uses: actions/cache@v3
        with:
          path: ~/.cache/pnpm
          key: \${{ runner.os }}-pnpm-\${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            \${{ runner.os }}-pnpm-
