# name: Docker Push

# on:
#   workflow_dispatch:
#     inputs:
#       service:
#         description: "Service to push (e.g., auth-service, inventory-service)"
#         required: true
#         default: "all"

# jobs:
#   docker-push:
#     runs-on: ubuntu-latest

#     permissions:
#       contents: read
#       packages: write

#     steps:
#       - name: Checkout repository
#         uses: actions/checkout@v3
#         with:
#           fetch-depth: 0

#       - name: Set up Node.js
#         uses: actions/setup-node@v3
#         with:
#           node-version: '18'

#       - name: Set up Docker Buildx
#         uses: docker/setup-buildx-action@v2

#       - name: Log in to Docker Hub
#         uses: docker/login-action@v2
#         with:
#           username: ${{ secrets.DOCKER_USERNAME }}
#           password: ${{ secrets.DOCKER_PASSWORD }}

#       - name: Get latest Git tag for the service
#         id: get_latest_tag
#         run: |
#           SERVICE="${{ github.event.inputs.service }}"
#           TAG=$(git tag --list "${SERVICE}-*" --sort=-v:refname | head -n 1)
#           echo "LATEST_TAG=${TAG}" >> $GITHUB_ENV

#       - name: Run docker-push.sh with dynamic service and tag
#         run: |
#           chmod +x ./scripts/release/docker-push.sh
#           ./scripts/release/docker-push.sh ${{ github.event.inputs.service }}
#         env:
#           DOCKER_TAG: ${{ env.LATEST_TAG }}
