name: Unit Tests

on:
  push:
    branches-ignore: [main, release/*]
  pull_request:

jobs:
  test-unit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: ./.github/actions/setup/setup-node.yml

      - name: Setup pnpm
        uses: ./.github/actions/setup/setup-pnpm.yml

      - name: Run Unit Tests
        run: bash scripts/ci/test-unit.sh
