name: System Alert

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *" # Runs daily

jobs:
  alert:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Run Alert Checks
        run: bash scripts/observability/alert.sh
