name: Rollback Deployment

on:
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * *" # Runs at 3am daily

jobs:
  rollback:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Initiate Rollback
        run: bash scripts/observability/rollback.sh
